### ISSUE TITLE
Failed to learn account: dbacl:warning: dirichlet measure did not converge

### ISSUE THREAD

**Issue by bascht** [johannesgerer/buchhaltung#36]
I'm not even sure if this is the correct place to report it, but during `buchhaltung match` I repeatedly stumble upon errors when learning from my accounts:

```
Done:     Assets:Receivable:Misc
Failed:   Expenses:Personal:Household
with Code ExitSuccess

And error:
dbacl:warning: dirichlet measure did not converge.
```

Do you have any hints what what could cause this / what I should look for in my imported ledger file?

**Comment by johannesgerer** [comment]
These messages are informational and usually do not indicate that something is not working. This needs to be improved ...


It usually happens if the account has not enough transaction to have the Bayesian classifier learn something, and implied that this account will not be suggested when matching transactions.

**Comment by bascht** [comment]
Oh alright, it sounded really exotic and googling for the error message did only bring up mathematical papers. :smile: 
Thanks for the explanation!
